spring:
  application:
    name: demo-project
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:coninsDetails
CoinAPI:
    host: https://api.coincap.io/v2/assets/  
CurrencyAPI:
        host: https://api.exchangerate.host/convert?from=  
Coin:
   type: bitcoin
Base:
   currencies: PKR,EUR,AED,INR,QAR         
        
server:
  port: 8080
  error:
      include-message: always      
